# Ustawienia świata
WORLD_WIDTH = 300.0
WORLD_HEIGHT = 300.0
MARGIN = 50

# Ustawienia misji
DEFAULT_EXPEDITION_NAME = "Rover-1"
MAX_STEPS = 50
TARGET_RADIUS = 10.0
RANDOM_EVENT_CHANCE = 0.15

# Pozycja startowa (domyślne)
DEFAULT_START_X = 0.0
DEFAULT_START_Y = 0.0
DEFAULT_START_ANGLE = 90.0
DEFAULT_INITIAL_FUEL = 100.0

# Koszty i bonusy energetyczne
TURN_BASE_COST = 2.0
MOVE_COST_PER_UNIT = 0.5
OUT_OF_BOUNDS_PENALTY = 5.0

# Elementy świata
FUEL_BONUS_VALUE = 30.0
OBSTACLE_PENALTY_VALUE = 20.0
SHORTCUT_MOVE_DISTANCE = 15.0
WEATHER_BONUS_VALUE = 10.0

# Liczba elementów świata
NUM_WORLD_ELEMENTS = 15

# Typy elementów
TYPE_FUEL = "PALIWO"
TYPE_OBSTACLE = "PRZESZKODA"
TYPE_SHORTCUT = "SKRÓT"

# Kolory i ustawienia widoku
COLOR_VEHICLE = "blue"
COLOR_BOUNDS = "red"
PEN_SIZE = 2
TURTLE_SPEED = 3
